name: CI

on:
  workflow_dispatch:
  push:
    branches: [master]
    tags: ['v*']
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Vet, build, and test
    runs-on: alpine
    steps:
      - uses: actions/toolkit/git-checkout@master
      - uses: actions/toolkit/go-setup@master
      - uses: actions/toolkit/node-setup@master
        with:
          working-dir: web
      - name: Install SPA dependencies
        working-directory: web
        run: pnpm install --frozen-lockfile
      - name: Build SPA
        working-directory: web
        run: pnpm build
      - name: Test SPA
        working-directory: web
        run: pnpm test
      - name: Test API Spec
        run: npx --yes @redocly/cli@2 lint --extends recommended-strict --format=github-actions internal/api/openapi.yaml
      - uses: actions/toolkit/go-vet@master
      - uses: actions/toolkit/go-test@master
      - name: Build image
        uses: actions/toolkit/docker-build@master
        with:
          file: Containerfile
