name: CI

on:
  workflow_dispatch:
  push:
    branches: [master]
    tags: ['v*']
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

enable-openid-connect: true

jobs:
  test:
    name: Vet, build, and test
    runs-on: alpine
    if: (github.ref == 'refs/heads/master')
    env:
      CGO_ENABLED: '0'
    steps:
      - uses: actions/toolkit/git-checkout@master
      - uses: actions/toolkit/go-setup@master
      - uses: actions/toolkit/node-setup@master
        with:
          working-dir: web
      - name: Install SPA dependencies
        working-directory: web
        run: pnpm install --frozen-lockfile
      - name: Install Go dependencies
        run: go mod download
      - name: Build SPA
        working-directory: web
        run: pnpm build
      - name: Test SPA
        working-directory: web
        run: pnpm test
      - name: Go Vet
        run: go vet
      - name: Go test
        run: go test
      - name: Build server binary
        run: go build -o todo .
      - name: Test API Spec
        run: npx --yes @redocly/cli@2 lint --extends recommended-strict --format=github-actions internal/api/openapi.yaml

  image:
    name: Build and push image
    needs: [test]
    if: success() && github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
    runs-on: alpine
    steps:
      - uses: actions/toolkit/git-checkout@master
      - uses: actions/toolkit/docker-login@master
        with:
          audience: u:1:b9293ba2-f8a7-439e-a788-a9107b7e3ea4
          ghcr: ${{ secrets.MIRROR_TOKEN }}
      - name: Build and push image
        uses: actions/toolkit/docker-push@master
        with:
          tags: ${{ steps.tags.outputs.tags }}
          file: Containerfile
          ghcr: true
