name: Image

enable-openid-connect: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  image:
    name: Build and push image
    runs-on: alpine
    steps:
      - uses: actions/toolkit/git-checkout@master
      - uses: actions/toolkit/docker-login@master
        with:
          audience: u:1:b9293ba2-f8a7-439e-a788-a9107b7e3ea4
          ghcr: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push image
        uses: actions/toolkit/docker-push@master
        with:
          file: Containerfile
          ghcr: true
